name: "push on AWS Server"

on: workflow_dispatch

jobs:
    deploy:
        runs-on: self-hosted
        steps:

        - name: setup node
          uses: actions/setup-node@v3
          with:
            node-version: '24'

        - name: checkout code
          uses: actions/checkout@v3

        - name: install depandencies
          run: npm install 

        - name: run tests
          run: npm test